### PR TITLE
#1: Double Linked List using single Pointer.

### PR DESCRIPTION
**Pull request by thebishaldeb**
#1 

### PROGRAM 
Double Linked List using single Pointer.
So basically one pointer is used to traverse 
back and forth in the linked list. This saves space
as we don't need two pointers that is being used normally

### CODE REVIEW

**Comment by thebishaldeb** [comment]
@rafi007akhtar check it out!

**Comment by rafi007akhtar** [comment]
Hi, please add an example input and output test case in the comments on top.

**Comment by thebishaldeb** [comment]
> Hi, please add an example input and output test case in the comments on top.

Done!

**Comment by rafi007akhtar** [comment]
Great!

**Review by rafi007akhtar — APPROVED** [review]

**Pull request merged**
